In [1]:
from typing import Dict, Any
import numpy as np

from torch_em.util.prediction import predict_with_halo
from model_ranking import load_h5

from pytorch3dunet.unet3d.model import get_model
from pytorch3dunet.unet3d.utils import load_checkpoint

In [2]:
VNC_path = "/scratch/talks/data/VNC/resized_pixels/test.h5"
VNC_data = load_h5(VNC_path, "raw")

In [3]:
print(VNC_data.shape)

(3, 589, 589)


In [4]:
model_cfg: Dict[str, Any] =  {
    "name": "UNet2d_as3d",
    "in_channels": 1,
    "out_channels": 1,
    "layer_order": "bcr",
    "f_maps": 32,
    "final_sigmoid": True,
    "is_segmentation": True
}
VNC_model_path = "/g/kreshuk/talks/segmentation_ModelSelection/experiments/VNC/BatchNorm/V_model1/best_checkpoint.pytorch"
VNC_model = get_model(model_cfg)
load_checkpoint(VNC_model_path, VNC_model)

/g/kreshuk/talks/pytorch-3dunet/pytorch3dunet/unet3d/utils.py:64: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(checkpoint_path, map_location="cpu")


{'num_epochs': 14,
 'num_iterations': 308,
 'model_state_dict': OrderedDict([('encoders.0.basic_module.SingleConv1.batchnorm.weight',
               tensor([0.9890])),
              ('encoders.0.basic_module.SingleConv1.batchnorm.bias',
               tensor([0.0048])),
              ('encoders.0.basic_module.SingleConv1.batchnorm.running_mean',
               tensor([0.0814])),
              ('encoders.0.basic_module.SingleConv1.batchnorm.running_var',
               tensor([0.2664])),
              ('encoders.0.basic_module.SingleConv1.batchnorm.num_batches_tracked',
               tensor(308)),
              ('encoders.0.basic_module.SingleConv1.conv.weight',
               tensor([[[[ 0.0132, -0.0737,  0.0364],
                         [ 0.2608, -0.0482, -0.1099],
                         [ 0.2757,  0.2131,  0.2782]]],
               
               
                       [[[-0.0558, -0.3422, -0.0465],
                         [ 0.1127, -0.0655, -0.0851],
                         

In [6]:
pred= predict_with_halo(
    VNC_data,
    VNC_model,
    gpu_ids=['cpu'],
    block_shape=(1,256,256),
    halo=(0,32,32),
    output=None,
    blockwise_prediction=True
)

predict with halo: 100%|██████████| 27/27 [00:01<00:00, 16.48it/s]


ValueError: all input arrays must have the same shape

In [ ]:
pred.shape

(3, 589, 589)